// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgahgurhbcmuxhdnbpcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYWhndXJoYmNtdXhoZG5icGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzUyMTAsImV4cCI6MjA2NjIxMTIxMH0.2bCH95mjP-k63veSBqzilVeeakt0xG-lTWRD0vtI6dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);